export const SET_DEFAULT_SELECTED_OPTIONS = "SET_DEFAULT_SELECTED_OPTIONS";
export const INITIALIZE_OPTIONS = "INITIALIZE_OPTIONS";
export const SET_OPTION_GROUP = "SET_OPTION_GROUP";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
